# Generated by Django 4.1.11 on 2023-09-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="star", max_length=100),
            preserve_default=False,
        ),
    ]
